### ISSUE TITLE
Make the nav bar sticky

### ISSUE THREAD

**Issue by Akki-58** [ankit071105/SmartBloom#5]
I would like to make the nav bar sticky so that users can scroll through content without losing their navigation context, leading to a more fluid interaction with the site.

![image](https://github.com/user-attachments/assets/302244a5-99cd-497c-a0ec-a78e094d6e2d)

![image](https://github.com/user-attachments/assets/82576b3f-01a5-4b86-a732-5d5d9737ed03)

Kindly assign me this issue with hacktoberfest-accepted label.

**Comment by harshkubavat7** [comment]
i can make navbar sticky

**Comment by harshkubavat7** [comment]
give me a chance.
